import type { IconType } from 'react-icons'
import {
  SiHtml5, SiCss, SiSass, SiBootstrap, SiTailwindcss,
  SiJavascript, SiTypescript, SiVuedotjs, SiReact, SiNextdotjs,
  SiPhp, SiSymfony, SiLaravel, SiPython, SiDjango, SiFastapi,
  SiNodedotjs, SiExpress, SiNestjs,
  SiDocker, SiGit, SiGithub, SiGitlab, SiLinux, SiNginx,
  SiPostgresql, SiMysql, SiMongodb, SiRedis, SiSqlite,
  SiGraphql, SiWebpack, SiVite, SiJest, SiVitest,
  SiWordpress, SiFigma, SiVercel, SiNetlify, SiCaddy,
  SiKubernetes, SiTerraform, SiAnsible, SiJenkins,
  SiRust, SiGo, SiSwift, SiKotlin, SiCplusplus, SiC,
  SiAngular, SiSvelte, SiNuxt,
  SiPrisma, SiSupabase, SiFirebase,
} from 'react-icons/si'
import { TbServer } from 'react-icons/tb'

export interface IconOption {
  key: string
  label: string
  defaultColor: string
}

export const ICON_REGISTRY: Record<string, IconType> = {
  SiHtml5, SiCss, SiSass, SiBootstrap, SiTailwindcss,
  SiJavascript, SiTypescript, SiVuedotjs, SiReact, SiNextdotjs,
  SiPhp, SiSymfony, SiLaravel, SiPython, SiDjango, SiFastapi,
  SiNodedotjs, SiExpress, SiNestjs,
  SiDocker, SiGit, SiGithub, SiGitlab, SiLinux, SiNginx,
  SiPostgresql, SiMysql, SiMongodb, SiRedis, SiSqlite,
  SiGraphql, SiWebpack, SiVite, SiJest, SiVitest,
  SiWordpress, SiFigma, SiVercel, SiNetlify, SiCaddy,
  SiKubernetes, SiTerraform, SiAnsible, SiJenkins,
  SiRust, SiGo, SiSwift, SiKotlin, SiCplusplus, SiC,
  SiAngular, SiSvelte, SiNuxt,
  SiPrisma, SiSupabase, SiFirebase,
  TbServer,
}

export const ICON_OPTIONS: IconOption[] = [
  { key: 'SiHtml5',       label: 'HTML5',           defaultColor: '#e34f26' },
  { key: 'SiCss',         label: 'CSS3',             defaultColor: '#1572b6' },
  { key: 'SiSass',        label: 'SCSS / Sass',      defaultColor: '#cc6699' },
  { key: 'SiBootstrap',   label: 'Bootstrap',        defaultColor: '#7952b3' },
  { key: 'SiTailwindcss', label: 'Tailwind CSS',     defaultColor: '#06b6d4' },
  { key: 'SiJavascript',  label: 'JavaScript',       defaultColor: '#f7df1e' },
  { key: 'SiTypescript',  label: 'TypeScript',       defaultColor: '#3178c6' },
  { key: 'SiReact',       label: 'React',            defaultColor: '#61dafb' },
  { key: 'SiNextdotjs',   label: 'Next.js',          defaultColor: '#ffffff' },
  { key: 'SiVuedotjs',    label: 'Vue.js',           defaultColor: '#42b883' },
  { key: 'SiNuxt',        label: 'Nuxt.js',          defaultColor: '#00dc82' },
  { key: 'SiAngular',     label: 'Angular',          defaultColor: '#dd0031' },
  { key: 'SiSvelte',      label: 'Svelte',           defaultColor: '#ff3e00' },
  { key: 'SiPhp',         label: 'PHP',              defaultColor: '#777bb4' },
  { key: 'SiSymfony',     label: 'Symfony',          defaultColor: '#a0aec0' },
  { key: 'SiLaravel',     label: 'Laravel',          defaultColor: '#ff2d20' },
  { key: 'SiPython',      label: 'Python',           defaultColor: '#3776ab' },
  { key: 'SiDjango',      label: 'Django',           defaultColor: '#092e20' },
  { key: 'SiFastapi',     label: 'FastAPI',          defaultColor: '#009688' },
  { key: 'SiNodedotjs',   label: 'Node.js',          defaultColor: '#339933' },
  { key: 'SiExpress',     label: 'Express',          defaultColor: '#a0aec0' },
  { key: 'SiNestjs',      label: 'NestJS',           defaultColor: '#e0234e' },
  { key: 'SiRust',        label: 'Rust',             defaultColor: '#ce422b' },
  { key: 'SiGo',          label: 'Go',               defaultColor: '#00add8' },
  { key: 'SiKotlin',      label: 'Kotlin',           defaultColor: '#7f52ff' },
  { key: 'SiSwift',       label: 'Swift',            defaultColor: '#fa7343' },
  { key: 'SiCplusplus',   label: 'C++',              defaultColor: '#00599c' },
  { key: 'SiC',           label: 'C',                defaultColor: '#a8b9cc' },
  { key: 'SiDocker',      label: 'Docker',           defaultColor: '#2496ed' },
  { key: 'SiGit',         label: 'Git',              defaultColor: '#f05032' },
  { key: 'SiGithub',      label: 'GitHub',           defaultColor: '#a0aec0' },
  { key: 'SiGitlab',      label: 'GitLab',           defaultColor: '#fc6d26' },
  { key: 'SiLinux',       label: 'Linux',            defaultColor: '#fcc624' },
  { key: 'SiNginx',       label: 'Nginx',            defaultColor: '#009639' },
  { key: 'SiCaddy',       label: 'Caddy',            defaultColor: '#00acd7' },
  { key: 'SiKubernetes',  label: 'Kubernetes',       defaultColor: '#326ce5' },
  { key: 'SiTerraform',   label: 'Terraform',        defaultColor: '#844fba' },
  { key: 'SiAnsible',     label: 'Ansible',          defaultColor: '#ee0000' },
  { key: 'SiJenkins',     label: 'Jenkins',          defaultColor: '#d33833' },
  { key: 'SiPostgresql',  label: 'PostgreSQL',       defaultColor: '#4169e1' },
  { key: 'SiMysql',       label: 'MySQL',            defaultColor: '#4479a1' },
  { key: 'SiMongodb',     label: 'MongoDB',          defaultColor: '#47a248' },
  { key: 'SiRedis',       label: 'Redis',            defaultColor: '#dc382d' },
  { key: 'SiSqlite',      label: 'SQLite',           defaultColor: '#003b57' },
  { key: 'SiPrisma',      label: 'Prisma',           defaultColor: '#2d3748' },
  { key: 'SiSupabase',    label: 'Supabase',         defaultColor: '#3ecf8e' },
  { key: 'SiFirebase',    label: 'Firebase',         defaultColor: '#ffca28' },
  { key: 'SiGraphql',     label: 'GraphQL',          defaultColor: '#e10098' },
  { key: 'SiVite',        label: 'Vite',             defaultColor: '#646cff' },
  { key: 'SiWebpack',     label: 'Webpack',          defaultColor: '#8dd6f9' },
  { key: 'SiJest',        label: 'Jest',             defaultColor: '#c21325' },
  { key: 'SiVitest',      label: 'Vitest',           defaultColor: '#6e9f18' },
  { key: 'SiWordpress',   label: 'WordPress',        defaultColor: '#21759b' },
  { key: 'SiFigma',       label: 'Figma',            defaultColor: '#f24e1e' },
  { key: 'SiVercel',      label: 'Vercel',           defaultColor: '#ffffff' },
  { key: 'SiNetlify',     label: 'Netlify',          defaultColor: '#00c7b7' },
  { key: 'TbServer',      label: 'Serveur générique', defaultColor: '#a0aec0' },
]
